#! /bin/bash
#
### BEGIN INIT INFO
# Provides:          wso2
# Product:           __PRODUCT__
# Product Version:   __PRODUCT_VERSION__
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the wso2 product server daemon
# Description:       Controls the main WSO2 product server daemon
### END INIT INFO
#

[ -z "$JAVA_HOME" ] && JAVA_HOME="__JAVA_HOME__"
WSO2_HOME="/usr/lib64/wso2/__PRODUCT__/__PRODUCT_VERSION__/__INTEGRATOR_TYPE__"

# defeine service commands
startcmd="${WSO2_HOME}/__SERVICE__.sh start"
restartcmd="${WSO2_HOME}/__SERVICE__.sh restart"
stopcmd="${WSO2_HOME}/__SERVICE__.sh stop"

case "$1" in
start)
   echo "Starting the WSO2 server ..."
   su -c "env JAVA_HOME=${JAVA_HOME} ${startcmd}" wso2 2>/dev/null
;;
restart)
   echo "Restarting the WSO2 server ..."
   su -c "env JAVA_HOME=${JAVA_HOME} ${restartcmd}" wso2 2>/dev/null
;;
stop)
   echo "Stopping the WSO2 server ..."
   su -c "env JAVA_HOME=${JAVA_HOME} ${stopcmd}" wso2 2>/dev/null
;;
*)
   echo "Usage: sudo service <PRODUCT_NAME> <start|stop|restart>"
exit 1
esac
